<a href="https://colab.research.google.com/github/alliekwolf/Linear_Algebra_Coding_Projects/blob/main/Practice_with_Gram_Schmidt_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import the numpy library...

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [ ]:
# How do I do a dot product?
np.dot([1, 2], [3, 4])

# How do I find the magnitude?
np.sqrt(np.dot([1, 2], [1, 2]))

2.23606797749979

In [ ]:
# Define the original vectors.

# Example from notes
# r1 = [2, 4, 0, 0]
# r2 = [1, 2, 3, 6]
# r3 = [2, -1, 2, -1]
# r4 = [1, 2, 3, 4]

# Example from homework
r1 = [3, 0, 3, 0]
r2 = [3, 2, 3, 3]
r3 = [-7, -4, -5, -6]
r4 = [-7, -3, -11, 2]

# Print r1.
r1

[3, 0, 3, 0]

In [ ]:
# Find the first nice basis vector u1.

# Step 1: Pick a new vector.
r1

# Step 2: Subtract the projection of r1 onto the nice basis u1, u2, u3...
#         and save this as a temporary vector n1.
n1 = r1
print(n1)

# Step 3: Find the magnitude of n1.
np.sqrt(np.dot(n1, n1))

# Step 4: Create the nice basis vector u1 = n1 / |n1|
u1 = n1/np.sqrt(np.dot(n1, n1))

# Print u1.
print(u1)

[3, 0, 3, 0]
[0.70710678 0.         0.70710678 0.        ]


In [ ]:
# Check that the magnitude of u1 = 1. (|u1| = 1)
print(np.dot(u1, u1))

1.0000000000000002


In [ ]:
# Find the second nice basis vector u2.

# Step 1: Pick a new vector.
r2

# Step 2: Subtract the projection of r2 onto the nice basis u1, u2, u3...
#         and save this as a temporary vector n2.
n2 = r2 - (np.dot(r2, u1) * u1)
print(n2)

# Step 3: Find the magnitude of n2.
np.sqrt(np.dot(n2, n2))

# Step 4: Create the nice basis vector u2 = n2 / |n2|
u2 = n2/np.sqrt(np.dot(n2, n2))

# Print u2.
print(u2)

[-4.4408921e-16  2.0000000e+00 -4.4408921e-16  3.0000000e+00]
[-1.23168186e-16  5.54700196e-01 -1.23168186e-16  8.32050294e-01]


In [ ]:
# Check that u2 is orthogonal (perpendicular) to u1 (dot product = 0).
print(np.dot(u2, u1))
# Check that the magnitude of u2 = 1. (|u2| = 1)
print(np.dot(u2, u2))

-1.741861189847285e-16
1.0


In [ ]:
# Find the third nice basis vector u3.

# Step 1: Pick a new vector.
r3

# Step 2: Subtract the projection of r3 onto the nice basis u1, u2, u3...
#         and save this as a temporary vector n3.
n3 = r3 - (np.dot(r3, u1) * u1) - (np.dot(r3, u2) * u2)
print(n3)

# Step 3: Find the magnitude of n3.
np.sqrt(np.dot(n3, n3))

# Step 4: Create the nice basis vector u3 = n3 / |n3|
u3 = n3/np.sqrt(np.dot(n3, n3))

# Print u3.
print(u3)

[-1.0000000e+00 -4.4408921e-16  1.0000000e+00 -8.8817842e-16]
[-7.07106781e-01 -3.14018492e-16  7.07106781e-01 -6.28036983e-16]


In [ ]:
# Check that u3 is orthogonal (perpendicular) to u1 and u2 (dot product = 0)
print(np.dot(u3, u1))
print(np.dot(u3, u2))
# Check that the magnitude of u3 = 1. (|u3| = 1)
print(np.dot(u3, u3))

0.894427190999916
-0.4385290096535148
1.0


In [ ]:
# Find the fourth nice basis vector u4.

# Step 1: Pick a new vector.
r4

# Step 2: Subtract the projection of r3 onto the nice basis u1, u2, u3...
#         and save this as a temporary vector n3.
n4 = r4 - (np.dot(r4, u1) * u1) - (np.dot(r4, u2) * u2) - (np.dot(r4, u3) * u3)
print(n4)

# Step 3: Find the magnitude of n3.
np.sqrt(np.dot(n4, n4))

# Step 4: Create the nice basis vector u3 = n3 / |n3|
u4 = n4/np.sqrt(np.dot(n4, n4))

# Print u3.
print(u4)

[-4.4408921e-16 -3.0000000e+00  4.4408921e-16  2.0000000e+00]
[-1.23168186e-16 -8.32050294e-01  1.23168186e-16  5.54700196e-01]


In [ ]:
# Check that u4 is orthogonal (perpendicular) to u1, u2, and u3. (dot product = 0)
print(np.dot(u4, u1))
print(np.dot(u4, u2))
print(np.dot(u4, u3))
# Check that the magnitude of u4 is 1. (|u4| = 1)
print(np.dot(u4, u4))

4.3370130851795835e-33
-1.203390859898517e-15
8.709305949236507e-17
1.0000000000000002
